import type { Metadata } from "next";
import RTK from "@omdb/providers/rtk";

import "@omdb/styles/index.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: ChildrenProps) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <RTK>{children}</RTK>
      </body>
    </html>
  );
}
